project:
  type: book

highlight-style: oblivion

book:
  title: "this is a test"
  author: "Jane Doe"
  date: "5/26/2023"
  #navbar:
   # background: danger
  
  site-url: https://jtr13.github.io/thisisatest
  repo-url: https://github.com/jtr13/thisisatest
  repo-branch: main
  repo-actions: [source, edit, issue]

  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cerulean
    code-link: true

editor: visual

