project:
  type: book

book:
  title: "graphs"
  author: "Jane Doe"
  date: "5/26/2023"
  site-url: https://jtr13.github.io/graphs
  repo-url: https://github.com/jtr13/graphs
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual

