project:
  type: book

book:
  title: "this is a test"
  author: "Jane Doe"
  date: "5/26/2023"
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual

